baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'ByNone'
paginate = 9
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = false
    style = "github"



